[build]
  base    = "frontend"
  command = "npm ci && npm run build && npm run export"
  publish = "frontend/out"

[build.environment]
  CLIENT_ID = "$CLIENT_ID"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
