[build]
  base    = "frontend"
  command = "npm ci && npm run build && npm run export"
  publish = "out"

[build.environment]
  CLIENT_ID                   = "$CLIENT_ID"
  NETLIFY_NEXT_PLUGIN_SKIP    = "true"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200